version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/hms
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - JWT_SECRET=bnjhn+vEH4axw/of+ecjSvCVDnmSOcYYlW1epsiiHok= # Use a shorter secret for readability
    depends_on:
      db:
        condition: service_healthy
    networks:
      - hms-network

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=hms
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hms-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d hms" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:


networks:
  hms-network:
    driver: bridge
