-- Add new columns to feedbacks table
ALTER TABLE feedbacks 
    ADD COLUMN IF NOT EXISTS entity_type VARCHAR(255),
    ADD COLUMN IF NOT EXISTS entity_id UUID,
    ADD COLUMN IF NOT EXISTS admin_response TEXT,
    ADD COLUMN IF NOT EXISTS type VARCHAR(50) NOT NULL DEFAULT 'GENERAL',
    ADD COLUMN IF NOT EXISTS submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP; 